---
name: rna-dge-salmon-deseq2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.8.5
  - conda-forge::pytest=6.1.2
  - conda-forge::datrie=0.8.2
  - conda-forge::git=2.29.2
  - conda-forge::jinja2=2.11.2
  - conda-forge::pygraphviz=1.6
  - conda-forge::flask=1.1.2
  - conda-forge::pandas=1.1.4
  - conda-forge::zlib=1.2.11
  - conda-forge::openssl=1.1.1h
  - conda-forge::networkx=2.5
  - bioconda::snakemake=5.29.0
  - conda-forge::ipython=7.19.0
  - conda-forge::bashlex=0.15
  - conda-forge::black=20.8b1
